### ISSUE TITLE
Updated ta_func_api.xml

### ISSUE THREAD

**Issue by hetsch** [trufanov-nok/ta-lib-rt#16]
Hi,

first thank you for this interesting library. I wanted to ask, if it would be possible to create an updated `ta_func_api.xml` with all the sugar that you've added. I'm thinking of e.g. `AcosStateInit`, `AcosBatchState`, aso.

Sorry for my ignorance if this is a massive task, but the build and code generation system is far beyond my rusty c knowledge.

Thank you very much!

**Comment by DavidFuchs42** [comment]
Hello
If you get me the code for AcosStateInit and, AcosBatchState or even if you tell me what they are I can add them.

**Comment by hetsch** [comment]
@DavidFuchs42 Sorry for my sloppy request. It seems, that it was too late yesterday. What I meant were these functions and structs:

- TA_[MYINDICATOR]_StateInit
- TA_[MYINDICATOR]_State
- TA_[MYINDICATOR]_StateFree
- TA_[MYINDICATOR]_StateSave
- TA_[MYINDICATOR]_StateLoad
- TA_[MYINDICATOR]_BatchState
- TA_[MYINDICATOR]_Data
- TA_[MYINDICATOR]_State

What do you think?

**Comment by trufanov-nok** [comment]
Hi,
It's doable, but isn't easy. The `ta_func_api.xml` is generated on the fly by gen_code (own tool of TA-Lib) based on function info declarations. It also has own xsd scheme for self-verification that seems to require changes too. But most importantly - I don't quite understand the purpose of ta_func_api.xml... It was designed 10 years ago by the authors of original TA-Lib. Perhaps they're expected that it will be integrated into some IDE's help system or parsed by something... Would be interesting to clear this up.
Could you explain a bit your use case of ta_func_api.xml ?

**Comment by hetsch** [comment]
My idea was to create a `emscripten` wrapper around TA-LIB - more or less a module/binding for JavaScript.

For such a wrapper, one has to create a WASM module and export the C functions which should be exposed to JavaScript via a tool called emscripten. This is one part of the journey. On the JavaScript side, these exported C functions can be invoked directly for calculating the specific indicator. A good explanation of emscripten could be found at https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html. The data between JavaScript and WASM is exchanged via pre allocated memory and this is where the XML file could help.

This XML file could be transformed to JSON and loaded in JavaScript. With it's information about data types one could dynamically create some JavaScript wrapper functions that allocate the necessary memory for all the parametes types of e.g  `TA_ACOS(int START_IDX,  int END_IDX, const double *IN_ARRAY, int  *BEG_IDX, int  *OUT_SIZE, double  *OUT_ARRAY) =  4 + 4 + 8 + 4 + 4 + 8 = 32 bytes` and result types e.g. `int TA_RetCode = 4 bytes`  of each specific indicator function in C.

**Comment by trufanov-nok** [comment]
Sounds interesting. Ok, I'll try to fix code generator and update the xml. It'll take a day or two.

**Comment by trufanov-nok** [comment]
Well, I've regenerated ta_func_api.xml. It's attached, pls check if it's suitable for your needs. Didn't form xsd for it yet. Some details:
1. I suspect that old ta_func_api.xml was created to let make Ruby wrapper. There is old Ruby wrapper for TA-Lib that's based on it.
2. In fact old ta_func_api.xml contained almost all info needed to generate all functions. Only info about State structure is missing and couldn't be guessed from it. The function info in old ta_func_api.xml technically isn't a description of a single function but description of whole indicator with all functions in it.

I'll try to explain how funcs are generated. Let's consider a TA-Lib RT fork. Each indicator has 8 functions with names TA_[Indicator]_[Suffix]  where [Suffix] is one of 8: {"Lookback", "", "StateInit", "State", "BatchState" "StateFree", "StateSave", "StateLoad"}.
Also there is a 3 groups of arguments: input, optional input, output. The arguments in input and output groups may be treated as arrays or single values. In case of arrays there will be 2 arguments added for each to handle array size and indexes. For input it's: int startIdx, int endIdx. For output it's int* outBegIdx and int* outNBElement.
Also there might be several hardcoded arguments in some functions: pointer to state, pointer to pointer to state, pointer to file descriptor (FILE*).

So, all functions are generated from indicator's arguments description as following:

1. Lookback is `int TA_[Indicator]_Lookback({optional input args})`
2. Regular function is `ret_code TA_[Indicator] ({input args as arrays}, {optional input args}, {output args as arrays})`.
3. StateInit function is pretty same as LookBack: `ret_code TA_[Indicator]_StateInit(pointer to pointer to state, {optional input args})`. In fact state struct remembers {optional input args}, so state and {optional input args} is never appear together except for initialization.
4. Sate function is `ret_code TA_[Indicator]_State(pointer to state, {input args}, {output args})`. So pretty the same as regular function but state object is used instead of optional args and other args are treated as not arrays.
5. BatchState function is a mix of regular function and State function: `ret_code TA_[Indicator]_BatchState(pointer to state, {input args as arrays}, {output args as arrays})`. We are using "as arrays" here.
6. StateFree is always `ret_code TA_[Indicator]_StateFree(pointer to pointer to state)`.
7. StateSave is `ret_code TA_[Indicator]_StateSave(pointer to state, pointer to file)`.
8. StateLoad is `ret_code TA_[Indicator]_StateLoad(pointer to pointer to state, pointer to file)`.
So we are using pointer to pointer to state in case we creating it (StateInit, StateLoad) and simple pointer to state otherwise.

As for Data struct and State structs. Data struct is always {input args} treated as no arrays.
Memory used in state is an array of Data structs. It's size is stored in Sate struct but basically equal to Lookback func result and set in StateInit. So it depends on {optional args}.
And the last is State struct. It always start with 2 int fields and pointer to memory. The fields are memory size and current index in memory. And after that some additional fields may be stored.

Let's recap with example.

You have Indicator "Id" with following args:
```
Input args: int inInt, double inReal
Optional args: int optTimeperiod
Output args: int outReal
```
If Input and output args are treated as arrays the function will have them as:
```
Input args: int startIdx, int endIdx, int inInt[], double inReal[]
Output args: int* outBegIdx, int* outNBElement, int outReal[]
```

The functions will be:
```
int TA_Id_Lookback(int optTimeperiod);
ret_code TA_Id(int startIdx, int endIdx, int inInt[], double inReal[],
                         int optTimeperiod,
                         int* outBegIdx, int* outNBElement, int outReal[]);
ret_code TA_Id_StateInit(void** state, int optTimeperiod);
ret_code TA_Id_State(void* state, int inInt, double inReal, int* outReal);
ret_code TA_Id_BatchState(void* state,
                        int startIdx, int endIdx, int inInt[], double inReal[],
                        int* outBegIdx, int* outNBElement, int outReal[]);
ret_code TA_Id_StateFree(void** state);
ret_code TA_Id_StateLoad(void** state, FILE* file);
ret_code TA_Id_StateSave(void* state, FILE* file);
```
Structs will be:
```
struct TA_Id_Data {
int inInt;
double inReal
}

struct TA_Id_State {
int mem_size;
int mem_idx;
TA_Id_Data* memory; // fixed size array of TA_Id_Data with size mem_size
{some additional fields}
}
```
Ok, everything is generated from arguments except for {some additional fields} in state structure. That's why old xml can't be used for RT. What could be in {some additional fields}? There may be integers, doubles and pointer to....  state objects of other indicators! For example in case your indicator is a moving average of 3 other moving averages the state object will contain 3 pointers to their states. Corresponding StateInit/StateFree/StateLoad/StateSave funcs of used indicators are called for these states. It's not automatic - it's coded by user. Everything about {some additional fields} is not automatically generated. Inner indicator's StateInit may get optInput args from indicator that uses it or the params may be hardcoded or partially hardcoded.

Another tough thing that may be in  {some additional fields} is a pointer to "circBuf". "circBuf" is another structure that holds one more buffer array apart of memory field. The structure is
```
TA_[Indicator]_STATE_CIRCBUF  { 
       int idx;   
       type* circbuf;  
       int size;
}
```
where `type*` is array of `type`. On practice it's array of double. Except of MoneyFlow indicator. In it's case it's array of another struct with two doubles.

I'm not sure if such details are required to make a wrapper.
[ta_func_api.zip](https://github.com/trufanov-nok/ta-lib-rt/files/5836417/ta_func_api.zip)

**Comment by hetsch** [comment]
Uh, that was fast. Thank you for all the work and the nice explanation! I just wanted to let you know that I'm currently working compiling the WASM module. A prototype works so far. The next step would be to incorporate your XML file and then I post back what how it worked out.

**Comment by trufanov-nok** [comment]
I've fixed some syntax errors in xml and updated xsd so now it validates.
Please use latest xml version from master branch: https://github.com/trufanov-nok/ta-lib-rt/blob/master/ta-lib-rt/ta_func_api.xml

**Comment by hetsch** [comment]
Hello again. I've worked the last days on getting the WASM - JavaScript bridge done. As it always is, it seems to be more complex than I initially thought. Nonetheless, I have a working version of your WIKI example of the "**original TA-Lib usage**" ready.

The version "**TA-Lib RT without dynamic result arrays allocation**" still gives me some headaches. 

I use the following library https://github.com/DeMille/wasm-ffi as a bridge between WASM and JavaScript that helps with some of the problems on how marshall and unmarshall specific data types in the shared memory between WASM (C) and JavaScript.

As far as I know, the follwoing structs

https://github.com/trufanov-nok/ta-lib-rt/blob/master/ta-lib-rt/c/include/ta_func.h#L14857-L14872

```c
struct TA_MACD_Data {
                               double       inReal;
                               };
struct TA_MACD_State {
                     size_t mem_size;
                     size_t mem_index;
                     struct TA_MACD_Data* memory;
                     void*        slowEMAState;
                     void*        fastEMAState;
                     void*        signalEMAState;
                     int          fastEMADelay;
                     int           optInFastPeriod; /* From 2 to 100000 */
                     int           optInSlowPeriod; /* From 2 to 100000 */
                     int           optInSignalPeriod; /* From 1 to 100000 */
                     };
```

might be replicated in JavaScript with something like

```javascript
const TA_MACD_Data = new Struct({
  inReal: "double",
});

const TA_MACD_State = new Struct({
  mem_size: "size_t",
  mem_index: "size_t",
  memory: types.pointer([TA_MACD_Data, 33]),
  slowEMAState: types.pointer("void"),
  fastEMAState: types.pointer("void"),
  signalEMAState: types.pointer("void"),
  fastEMADelay: "int",
  optInFastPeriod: "int",
  optInSlowPeriod: "int",
  optInSignalPeriod: "int",
});

const memSizeP = library.TA_MACD_Lookback(12, 26, 9);  // = 33

// Memory used in state is an array of Data structs. 
// It's size is stored in Sate struct but basically equal to Lookback func result and set in StateInit
stateMemoryPtr = new Pointer(
  [TA_MACD_Data, memSizeP],
  // allocate memory 
  // double * memSizeP, 8 * 33 == 264  (
  Array(memSizeP).fill(new TA_MACD_Data())
);
// allocate shared memory
library.utils.allocate(stateMemoryPtr);
       
statePtr = new Pointer(
  TA_MACD_State,
  new TA_MACD_State({
    // 264 bytes
    mem_size: stateMemoryPtr.size(),
    // gets incremented every loop but initial value should be 0?
    mem_index: 0,
    memory: stateMemoryPtr,
    slowEMAState: new Pointer("void", 0),
    fastEMAState: new Pointer("void", 0),
    signalEMAState: new Pointer("void", 0),
    fastEMADelay: 0,
    optInFastPeriod: 12,
    optInSlowPeriod: 26,
    optInSignalPeriod: 9,
  })
);
// allocate shared memory
library.utils.allocate(statePtr);

```

Passing the `statePtr` to `library.TA_MACD_StateInit(statePtr, 12, 26, 9)` works without errors, what is the good thing. If I dump the state object via `console.log(statePtr.deref())` to the browser console, this is my output.

![Bildschirmfoto von 2021-01-27 12-45-08](https://user-images.githubusercontent.com/439359/105986864-c10e3d80-609d-11eb-80ea-07b1759a7635.png)

If I further use the same state object and calling `TA_MACD_State` in a loop, I always get `TA_NEED_MORE_DATA` as return code and the state object never changes it's values (like mem_idx - that should increment, if I understand correctly).

```
for (let i = 0; i < data.length; i++) {
  console.log(statePtr.deref());
  retCode = library.TA_MACD_State(
    statePtr, // function state object
    data[i], // data value
    outMACDPtr,
    outMACDSignalPtr,
    outMACDHistPtr
  );
  // retCode is always TA_NEED_MORE_DATA
} 
```

I then had a look at `ta_MACD.c` and especially this snippet of code:

https://github.com/trufanov-nok/ta-lib-rt/blob/10f5e414e9c1795e419b3803a83f63b3f4a37e93/ta-lib-rt/c/src/ta_func/ta_MACD.c#L588-L601

Does this mean, that you allocate new memory for the state object each time TA_MACD_StateInit is called and you don't use the state pointer that was passed as argument to the function. If I understand that correctly I'm not able to pass a shared memory pointer from JavaScript to C/WASM and that might be the problem.

I hope this all makes some sense, and please forgive my ignorance because it is the first time I actually work with C code and more or less memory pointers and all the fuzz.

Thank's again!

**Comment by trufanov-nok** [comment]
> Does this mean, that you allocate new memory for the state object each time TA_MACD_StateInit is called
That's correct. Init function not just initialize state object values but allocates whole object too.

> and you don't use the state pointer that was passed as argument to the function.

Note that Init() function accepts not a pointer but "pointer to pointer". It stores the address of allocated object to the pointer it receives. Passing pointers to objects is one of ways in C to return values in them. In other words:

```
void* state;
state = 0;
TA_[XXX]Init(&state);
state != 0 after that.
```
Init function could be rewritten as
```
void * TA_[XXX]_Init()
{
  void* state = [alocate state object];
  return state;
}
```
and used as:
```
void * state = TA_[XXX]_Init();
if (state != 0) {
 // we are OK.
}

```
But I decided to keep original TA-Lib's function style of returning error values as a result of function instead.

Technically TA-Lib RT was designed to hide structure of state objects from the user. It allocates state by itself, it free it by itself and save/load to file if needed.
From user's perspective state object is a untyped pointer. So it's just an address in memory where something is stored. Thus it's just a number.  
For example in python the state object is just an integer (on python side).

So `void* state` is just an int32 on 32-bit machine or int64 on 64-bit machine. `size_t` is used instead which is a template for int32 or int64 depending on architecture.

Thus you may just call something like
```
size_t state = 0;
TA_[XXX]_Init( &state );
// state != 0 here
```

So as TA-Lib RT doesn't expect user to access the state object directly, and pointer to it is just a number you may treat it as "ID" of a state object in TA-Lib RT's memory.
I'm not sure if this memory is accessible in JS, but it doesn't matter as you are receiving and passing just an id of the object. Unless the ta-lib-rt dll is unloaded between calls - in this case it'll clear it's heap memory and id (which is a pointer)  will point to nothing. Which will cause a seg fault.

I suppose the dll isn't unloaded from RAM. So, you don't need a shared memory at all.

**Comment by hetsch** [comment]
I've got you - thank's once again! It's working so far! Pointer to a Pointer was too much for my nutshell. The hard part is done (I suspect :))

![Bildschirmfoto von 2021-01-27 15-56-15](https://user-images.githubusercontent.com/439359/106009226-659d7900-60b8-11eb-9863-816e3b52dece.png)
