### ISSUE TITLE
ta-lib macd not correct 

### ISSUE THREAD

**Issue by 19504643** [trufanov-nok/ta-lib-rt#19]
[https://stackoverflow.com/questions/66102071/ta-lib-c-calculated-macd-not-matched-web](https://stackoverflow.com/questions/66102071/ta-lib-c-calculated-macd-not-matched-web)

that's what I'm suffering.
I have used Excel to test all the data, it's all the same with website, but ta-lib not matched
I have tested with 1000 more data, it's still not matched, could u please have a try, thanks

**Comment by trufanov-nok** [comment]
Could you attach the excel file and point to the website you refer to?

**Comment by 19504643** [comment]
website is a bitcoin trading system, you can sign in with my fee discounts link: https://www.huobi.pro/en-us/topic/invited/?invite_code=h9263

and the Kline is https://www.huobi.pro/en-us/exchange/btc_usdt

Excel calculated ok
[huobi_day_macd_01.xlsx](https://github.com/trufanov-nok/ta-lib-rt/files/5995515/huobi_day_macd_01.xlsx)

![image](https://user-images.githubusercontent.com/4372492/108202517-2cf33b80-715c-11eb-81ce-0316ee91fd7f.png)

**Comment by trufanov-nok** [comment]
Well, I have found the reason. Consider the following code:
```
import talib
import numpy as np

data = np.array([11085.65, 11380.92, 11211.78, 11662.52, 11836.86, 11641.2, 11735.19, 11566.98, 11919.16, 11484.56, 11580, 11495, 11737.66, 11852.78, 11860.88, 12405.37, 11935.13, 11727.11, 11851.54, 11721.83, 11582.3, 11653.19, 11764.29, 11419.18, 11474.34, 11322.79, 11531.71, 11500.59, 11616.25, 11740.01, 12040.03, 11330.3, 10667.98, 10425.34, 10275.27, 10173.2, 10145, 10095.75, 10245.61, 10415.81, 10316.91, 10360.86, 10279.61, 10697.54, 10785.95, 11004.54, 10838.48, 10897, 11089.65, 10835.82, 10418.42, 10450.68, 10452.67, 10548.08, 10647.4, 10721.15, 10757.29, 10901.96, 10724.96, 10777.82, 10715.13, 10513.68, 10543.8, 10592.47, 10724.58, 10734.58, 10629.45, 10895.78, 11084.28, 11349.9, 11403.62, 11546.99, 11384.69, 11319.78, 11397.07, 11332.06, 11336.85, 11448.17, 11806.89, 11923.48, 12729.51, 12931.8, 12921.88, 13101.33, 12942.24, 12979.23, 13606.5, 13220.25, 13435.23, 13551, 13854.39, 13797.96, 13492.15, 13708.92, 13911.95, 15077.18, 15411.23, 15342.63, 15354.6, 15004.24, 15168.03, 15666.22, 16122.33, 16098.79, 15950.15, 16026.15, 16450.98, 17318.57, 17871.06, 18046.78, 18655.81, 18784.06, 18294.73, 18269.55, 19358.42, 19129.39, 16905.43, 16502.76, 17505, 18116.34, 19306.92, 19265.5, 18891.06, 19533.84, 18945.51, 19107.67, 19126.33, 19213, 18806.82, 18347.36, 18134.91, 18106.72, 18401.98, 19215.36, 19198.7, 19406.28, 20659.69, 23329.31, 22553.6, 23551.1, 23873.04, 23099.56, 23341.65, 23450.3, 23230.15, 24019.43, 25625.24, 27360.51, 26911.93, 26617.04, 28153.95, 28779.14, 29190.91, 31695.17, 33506.67, 31737.83, 32091.45, 34555.33, 38950, 40829.87, 40513.11, 39674.77, 31580.01, 33834.78, 34677.01, 39551.87, 35627.27, 37460.76, 35732.04, 36408.31, 37328.12, 34183.43, 31392.34, 32457.32, 31876.57, 31952.8, 34459.95, 31757.38, 30327.18, 31924.17, 37118.35, 34212.01, 32858.22, 33156.65, 34719.71, 36844.22, 36564.58, 37952.37, 40849.89, 37924.41, 43627.16, 46784.38, 44345.02, 47951.62, 47018.46, 47081.58, 48546.17, 47947, 48958.14])

ema12 = talib.EMA(data, 12)

ema26 = talib.EMA(data, 26)

excel_macd = ema12[1] - ema26[1]
talib_macd = talib.MACD(data, 12, 26)
```

excel_macd contains 
```
array([          nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,  -42.88222505,  -45.74638855,  -49.95157204,
        -43.45054404,  -27.98939055,    8.37623559,  -19.84427084,
...
```

which is equal to your excel  MACD column.
The `talib_macd` is 
```
array([          nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan, -140.09395204, -215.11112551, -279.57619161,
       -329.14652896, -368.16150519, -382.57857768, -375.93692703,
       -374.33863177, -365.31445592, -360.56258646, -319.39149116,
...
```

which differs. The reason is following:

In your excel the 12-day EMA is calculated from the 1st day and its first value is the average on 12th day (8/13/2020) and the 26-day EMA is calculated from 1st day and first value is average on 26th day (26/13/2020).  TA-Lib postpones the 12 day EMA calculation start to get its first value on the same day as first value of 26-day EMA. That means 12-day EMA is calculated from 8/16/2020 and it's first value is the average on (26/13/2020) as it's in 26-day EMA. So to adjust your excel to TA-Lib results you need to copy formula `=AVERAGE(B19:B30)` into the cell `C30`.

Another note is that TA-Lib's MACD outputs 3 arrays at once: macd, signal, histogram. And thus TA-Lib it starts the output at the point it got meaningful values for all 3 result arrays. Thus you're getting result starting not from the point where 26-day EMA can be calculated, but from the point where Signal can be calculated (9 days later). So shall compare `talib_macd[1]` with excel starting from cell `E38` instead of `E30`.
![Screenshot_20210217_165803](https://user-images.githubusercontent.com/5746456/108214672-7c783e00-7141-11eb-9fbb-3938b726247c.jpg)

**Comment by 19504643** [comment]
Tks, but how to use C++ lib to get ema12 and ema26 first and then get MACD using talib.MACD(data, 12, 26), c++ lib does not have this function
